### ISSUE TITLE
Answer results are lost for multiple Selections in SelectionAnswers

### ISSUE THREAD

**Issue by harmsk** [leeper/MTurkR#63]
If I have a question that allows for multiple selections within a SelectionAnswer. mTurk will return the results deliminted by: |. For example: A|B|C. However if I use GetAssignments with MTurkR only the first Selection is returned. Example: A.

**Comment by leeper** [comment]
Thanks for this. I will investigate.

**Comment by leeper** [comment]
@harmsk I think this should now be fixed. Install the latest version from GitHub and let me know if you still encounter problems.

You should see something like: 

```
GetAssignments(hit = "3BVS8WK9Q0VPS7SBME0O6P92J4OIBZ")
1 of 1 Assignments Retrieved
                    AssignmentId       WorkerId                          HITId AssignmentStatus     AutoApprovalTime           AcceptTime           SubmitTime
1 3S4AW7T80BIAKTD2I5SGFBR76L0L4A A1RO9UJNWXMU65 3BVS8WK9Q0VPS7SBME0O6P92J4OIBZ        Submitted 2015-02-02T09:55:00Z 2015-01-03T09:54:54Z 2015-01-03T09:55:00Z
  ApprovalTime RejectionTime RequesterFeedback ApprovalRejectionTime SecondsOnHIT question1
1         <NA>          <NA>              <NA>                    NA            6       1;2
```

With multiple selection answers semicolon-separated. This was the intended current behavior, but there was a problem that the code wasn't correctly identifying when there were multiple selections and thus only provided the first one (as you were seeing).

**Comment by harmsk** [comment]
Thank you. This works great.
