### ISSUE TITLE
HitStatus ignores verbose=FALSE

### ISSUE THREAD

**Issue by az0** [leeper/MTurkR#77]
I installed MTurkR version 0.6 from CRAN on R 3.1.2, and the following code prints the data frame despite the verbose option.

````R
	hstatus <-HITStatus(hit=hitid, verbose=FALSE)
````

**Comment by az0** [comment]
Line 11 of HITStatus calls SearchHITs  with verbose hard coded to TRUE.

**Comment by leeper** [comment]
@az0 What is printed is not the same as the (invisible) return value of `HITStatus`. I wrote this initially to just be an interactive tool, so it actually shouldn't have a `verbose` argument. But are you saying you'd like to be to access what is printed on screen programmatically and suppress the printing of that status message?

**Comment by az0** [comment]
That is what I expected (a "silent mode"), but what you wrote makes sense.  This was not a real problem---I misunderstood.   

Thank you for the useful package, and have a nice day.
