### ISSUE TITLE
expired HIT cannot be extended

### ISSUE THREAD

**Issue by lilchow** [leeper/MTurkR#79]
I have a HIT which went expired yesterday. And I used the following command to both add new assignments and extend the survey.

ExtendHIT(hit=currentHIT$HITId,add.seconds = seconds(days=3),add.assignments = 100)

The command ran without any issues. However, when I checked the HIT in GUI, the HIT remains expired though the number of available assignments did increased. 

Is this a bug of the package or the Mturk api? Thanks!

**Comment by leeper** [comment]
You can only specify either `add.seconds` or `add.assignments`, not both. (I don't recall at the moment if this is an API restriction or just something I setup in the package...I'll check that.) If `add.assignments` is specified, the function only extends the assignments not the time. The function should warn you about this, though, so I'll add that. The temporary fix is just to call it again with only the `add.seconds` argument and you should be good to go.

**Comment by leeper** [comment]
@lilchow Yes, turns out this was just a small error in the package. Should be fixed now, if you reinstall from GitHub.

**Comment by lilchow** [comment]
Does it mean that I now can do both in one command? That's really neat! Thanks a lot!

**Comment by leeper** [comment]
Yes, you should be able to. Let me know if you encounter problems with it,
though.
