### ISSUE TITLE
Creating Qualification through the Wizard gives error

### ISSUE THREAD

**Issue by seanchrismurphy** [leeper/MTurkR#85]
Trying to create a new qualification through the wizard with the latest version of MTurkR, I get the error 'object of type 'closure' is not subsettable' printed to the console. As far as I can tell, the qualification is still created and I am still able to assign workers to it, so the wizard appears to be worker, but the source of the error might be worth investigating.

This happened while leaving all fields blank except the Public Name and Public Description.

**Comment by leeper** [comment]
This was just a typo in the name of the tcl/tk window, which was causing it not to close after creating the qualification. You're correct that it did not affect the `CreateQualification` process at all. Thanks!
