### ISSUE TITLE
Switch from RCurl to curl

### ISSUE THREAD

**Issue by leeper** [leeper/MTurkR#86]
This reduces dependencies (namely methods and bitops) and will hopefully mean a performance enhancement.

- [x] DESCRIPTION
- [x] NAMESPACE imports
- [ ] Code updates
  - [x] Switch `RCurl::curlEscape` and `RCurl::curlUnescape` to `curl::curl_escape` and `curl::curl_unescape`
  - [x] Find replacement for RCurl::base64Encode`. Maybe `base64::base64encode`

**Comment by jeroenooms** [comment]
Simon's [base64enc](http://cran.r-project.org/web/packages/base64enc/index.html) package is by far the best base64 implementation available.

**Comment by leeper** [comment]
Thanks, @jeroenooms!
