### ISSUE TITLE
HITStatus() doesn't work properly

### ISSUE THREAD

**Issue by lilchow** [leeper/MTurkR#90]
I have been encountering this issue the whole time. Whenever I use HITStatus to check the status of my newly launched HIT, it spills correct information for Assignment Pending and Assignment Available. However, Assignment Completed is always 0 regardless of whether a HIT is newly launched or newly completed. Any idea what is going on here? Thanks!

**Comment by leeper** [comment]
I'm travelling at the moment, but give me a few days to investigate.

**Comment by leeper** [comment]
As far as I can tell, there's nothing MTurkR-specific here because everything in the API responses is being parsed correctly. The issue is probably a lag in how AWS accumulates those results. So I'm closing this for now.
